# -*- coding: utf-8 -*-
"""data_pipeline_async.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1TUMtlGCVIt8G3VK63gJNdIcPR-zx4B
"""

import pandas as pd
import time
import requests
import sys
import httpx
import asyncio
from tqdm.asyncio import tqdm

#非同期通信 同時接続数の設定
sem = asyncio.Semaphore(3)

#データcsvファイルを読み込む
df = pd.read_csv('/content/sample_data/data.csv')

from google.colab import userdata
#APIキーを取得
app_id = userdata.get('ESTAT_APP_ID')

kokudo_API_1 = "https://mreversegeocoder.gsi.go.jp/reverse-geocoder/LonLatToAddress"

#市区町村コードを取得
async def latlon_to_municd(client, lat, lon):
    params = {'lat':lat,'lon':lon}
    # print(params)
    r = await client.get(kokudo_API_1,params=params)
    r.raise_for_status()
    return r.json()['results']['muniCd']

kokudo_API_2 = "https://cyberjapandata2.gsi.go.jp/general/dem/scripts/getelevation.php"


#緯度経度から標高を取得
async def latlon_to_elevation(client, lat, lon):
    params = {'lat':lat,'lon':lon,'outtype':'JSON'}
    r = await client.get(kokudo_API_2,params=params)
    r.raise_for_status()
    elevation = r.json()['elevation']

    return (elevation)

#muni_cdから市町村名を取得

ESTAT_API = "https://dashboard.e-stat.go.jp/api/1.0/Json/getRegionInfo"


#市区町村コードから市区町村名を取得
#市区町村コードから親地域コードを作成し、県名を取得
async def muniCd_to_Name(client, muni_cd):

    muni_cd = str(muni_cd)  #文字列に変換(元々はint64)
    parent_region_code = muni_cd[:2] + "000"
    params = {'ParentRegionCode':parent_region_code}

    #APIから取得する
    r = await client.get(ESTAT_API,params=params)
    r.raise_for_status()
    data = r.json()

    #県情報
    prefecture= (data['GET_META_REGION_INF']['METADATA_INF']['CLASS_INF']['CLASS_OBJ'][0])
    # print(prefecture)

    prefecture_name = prefecture['@name']

    #市区情報
    regions = (data['GET_META_REGION_INF']['METADATA_INF']['CLASS_INF']['CLASS_OBJ'][0]['CLASS'])

    #regionCodeに合致したらNameを取得
    muni_name = next((columns['@name'] for columns in regions if columns['@regionCode'] == muni_cd),None)

    #県の直下で値が取得できなかった場合、
    #郡レベルでjsonを再取得
    if not muni_name:

        params = {'RegionCode':muni_cd}
        r = await client.get(ESTAT_API,params=params)
        r.raise_for_status()
        data = r.json()
        objs = (data['GET_META_REGION_INF']['METADATA_INF']['CLASS_INF']['CLASS_OBJ'])

        #regionCodeに合致したらNameを取得
        # import json
        # print(json.dumps(objs, indent=2, ensure_ascii=False))
        muni_name = next((c['@name'] for obj in objs for c in obj['CLASS'] if c['@regionCode'] == muni_cd and c['@toDate'] == '999912'),None)

        if not muni_name:
            print("値が取れませんでした。")

            #値が取得できない場合は、Noneとprefecture_nameを返す
            await asyncio.sleep(0.2)
            return (None,prefecture_name)

    #ifの外でreturn(muni_nameが最初に取得できている時もこれで対応)
    return (muni_name,prefecture_name)

ESTAT_API_2 = "https://api.e-stat.go.jp/rest/3.0/app/json/getStatsData"


#e-statから情報を取得
async def fetch_estat_value(client, STATS_DATA_ID, muni_cd, cat_code, date):

    year = int(date[:4])
    params = {'appId':app_id,
            'statsDataId':STATS_DATA_ID,
            'cdArea':muni_cd,
            'cdCat01':cat_code,
            'time':year}

    r = await client.get(ESTAT_API_2,params=params)
    r.raise_for_status()
    values = (r.json()['GET_STATS_DATA']['STATISTICAL_DATA']['DATA_INF']['VALUE'])
    if not values:
        print("値が取得できませんでした")
        return None

    #入力したyearの直近の国勢調査の人口or土地面積を取得（配列の最後が直近）
    return float(values[-1]['$'])

async def latlon_process_row(client, row):

    #並列
    async with sem:
        try:
            municd, elevation = await asyncio.gather(
                latlon_to_municd(client, row['lat'], row['lon']),
                latlon_to_elevation(client,row['lat'], row['lon'])
            )
            await asyncio.sleep(0.2)
            return {"municd":municd, "elevation":elevation}
        except Exception as e:
            print(f"エラー：{row['lat'], row['lon']} {e}")
            return {"municd":None, "elevation":None}

async def municd_process_row(client, STATS_DATA_ID, STATS_DATA_ID_2, row):

    #並列
    async with sem:
        try:
            (muniname, prefecture), population, area = await asyncio.gather(
                muniCd_to_Name(client, row['municd']),
                fetch_estat_value(client, STATS_DATA_ID, row['municd'], 'A1101', row['date']),
                fetch_estat_value(client, STATS_DATA_ID_2, row['municd'], 'B1101', row['date'])
            )
            await asyncio.sleep(0.2)
            return {"muniname":muniname, "prefecture":prefecture, "population":population, "area":area}
        except Exception as e:
            print(f"エラー：{row['municd']} {e}")
            return {"muniname":None, "prefecture":None, "population":None, "area":None}

#メイン

#データフレームを初期化(不要な列が存在しないようにする)
df = df[['lat', 'lon', 'date', 'targetVal']].copy()

df['municd'] = None
df['elevation'] = None
STATS_DATA_ID = '0000020201' #社会・人口統計体系
STATS_DATA_ID_2 = '0000020102' #土地面積
final_results = []

#最初のループでlat,lonから市区町村コードと標高を取得
#100件ずつClientをリセットして実行
#retry機能を追加
counter = 0
max_retries = 3
while max_retries > counter:
    # municdが欠損している行だけを抽出
    # 初回は df 全体、2回目以降は失敗した行だけが対象になる
    target_index = df[df['municd'].isna()].index

    if len(target_index) == 0:
        print("全てのmunicdを取得完了しました。")
        break

    print(f"残り{len(target_index)}件のmunicd取得を開始します")
    retry_df = df.loc[target_index]

    chunk_size = 100
    for i in range(0, len(retry_df), chunk_size):
        chunk = retry_df.iloc[i : i + chunk_size]

        async with httpx.AsyncClient(timeout=30) as client:
            tasks = [latlon_process_row(client, row) for _, row in chunk.iterrows()]

            # 100件分を並行実行（進捗バー付き）
            results = await tqdm.gather(*tasks, desc=f"chunk {i//chunk_size + 1}")
            final_results.extend(results)

            # チャンクの合間にサーバーを休ませる
            await asyncio.sleep(1)
    # 取得した結果を元の df の正しい位置（index）に書き戻す
    res_df = pd.DataFrame(final_results, index=target_index)
    df.update(res_df) # updateを使うと、indexが一致する場所だけ上書きしてくれます

    #サーバへの負荷を考慮
    if len(df[df['municd'].isna()]) > 0:
        print("一部失敗したため、3秒後にリトライします...")
        await asyncio.sleep(3)

    counter += 1

#2回目のループで市区町村名、県名、人口、土地面積を取得
counter = 0
df['muniname'] = None
df['prefecture'] = None
df['population'] = None
df['area'] = None

while max_retries > counter:

    # municdが欠損している行だけを抽出
    # 初回は df 全体、2回目以降は失敗した行だけが対象になる
    target_index = None
    target_index = df[df['muniname'].isna()].index
    if len(target_index) == 0:
        print("全てのmuninameを取得完了しました。")
        break

    print(f"残り{len(target_index)}件のmuniname取得を開始します")
    retry_df = None
    retry_df = df.loc[target_index]

    final_results = []
    for i in range(0, len(retry_df), chunk_size):
        chunk = retry_df.iloc[i : i + chunk_size]

        async with httpx.AsyncClient(timeout=30) as client:
            tasks = [municd_process_row(client, STATS_DATA_ID, STATS_DATA_ID_2, row) for _, row in chunk.iterrows()]
            results = await tqdm.gather(*tasks, desc=f"chunk {i//chunk_size + 1}")
            final_results.extend(results)

            # チャンクの合間にサーバーを休ませる
            await asyncio.sleep(1)
    # 取得した結果を元の df の正しい位置（index）に書き戻す
    res_df = None
    res_df = pd.DataFrame(final_results,index=target_index)
    df.update(res_df)

    counter += 1

# #人口密度を算出(e-statの土地面積はha単位なので最後に100を掛ける)
df['population_density'] = (df['population'] / df['area']) * 100

df = df[['lat','lon','date','elevation','municd','muniname','prefecture','population','area','population_density','targetVal']]

#csv出力
df.to_csv('/content/sample_data/mydata.csv')
print(df)